### ISSUE TITLE
Issue with podules

### ISSUE THREAD

**Issue by Neelix57** [sarah-walker-pcem/arculator#11]
I compiled Arculator v2.1 under Xubuntu 18.04.

When selecting a podule, the configure buttons remain greyed out, and when closing and reopening the
machine configuration window, the podule selection boxes returns to none.

Got Failed to open SO errors, when launching Arculator.

Here is a log:
`[00000000]: Looking for podules in ./podules/
[00000000]: podule_probe returned 0x7f7065d6ad60
[00000000]: podule_probe returned 0x7f7065b64d60
[00000000]: Failed to open SO . ./podules/./..so: cannot open shared object file: No such file or directory
[00000000]: Failed to open SO common ./podules/common/common.so: cannot open shared object file: No such file or directory
[00000000]: podule_probe returned 0x7f706595ed60
[00000000]: podule_probe returned 0x7f7065758d60
[00000000]: Failed to open SO .. ./podules/../...so: cannot open shared object file: No such file or directory
[00000000]: podule_probe returned 0x7f7065531d20
[00000000]: Failed to open SO pccard ./podules/pccard/pccard.so: cannot open shared object file: No such file or directory
HDA ATI SB: PCM device=0:0:0
[00000000]: podule_probe returned 0x7f706531bd40
[00000000]: podule_probe returned 0x7f70650efd20
[00000000]: podule_probe returned 0x7f7064ec8d60
[00000000]: podule_probe returned 0x7f7064cbfd80
[00000000]: Loading ROM set 0 from ./roms/arthur030
[00000000]: Found ROM030
[00000000]: Loading ROM set 1 from ./roms/arthur120
[00000000]: Found ROM120
[00000000]: Loading ROM set 2 from ./roms/riscos200
[00000000]: Found ROM200
[00000000]: Loading ROM set 3 from ./roms/riscos201
[00000000]: Found ROM201
[00000000]: Loading ROM set 4 from ./roms/riscos300
[00000000]: Found ROM300
[00000000]: Loading ROM set 5 from ./roms/riscos310
[00000000]: Found ROM310
[00000000]: Loading ROM set 6 from ./roms/riscos311
[00000000]: Found ros311
[00000000]: Loading ROM set 7 from ./roms/riscos319
[00000000]: Found ROM319
[00000000]: Loading ROM set 8 from ./roms/arthur120_a500
[00000000]: Found A500_Arthur_ROM.rom
[00000000]: Loading ROM set 9 from ./roms/riscos200_a500
[00000000]: Found ROM200.A500Build
[00000000]: Loading ROM set 10 from ./roms/riscos310_a500
[00000000]: Found a500_riscos310`

**Comment by Sophira** [comment]
I did some bisecting on this one; it seems like podule selection stopped working in this manner from commit dcfa885239f8c7459002c6957ce2ad63b7a97843 onwards.

**Comment by sarah-walker-pcem** [comment]
Fixed in c055724.

**Comment by sjnewbury** [comment]
This isn't fixed.  The problem is append_filename() just uses `sprintf(dest, "%s%s", s1, s2);` where in this case the source and destination buffers are the same.  This is undefined behaviour, and works sometimes...

It isn't working for me at the at the moment, could be my compiler, or some other change in the code just moving things around.  Could be anything.

**Comment by sjnewbury** [comment]
Using strdup() as below is enough to make this reliable.  Is it worth sending a pull request for this?

```
 void append_filename(char *dest, const char *s1, const char *s2, int size)
 {
-       sprintf(dest, "%s%s", s1, s2);
+       char *tmp_s1 = strdup(s1);^M
+       char *tmp_s2 = strdup(s2);^M
+       sprintf(dest, "%s%s", tmp_s1, tmp_s2);^M
+       free(tmp_s1);^M
+       free(tmp_s2);^M
 }
 
```

**Comment by Sophira** [comment]
Oh, interesting. In that case, that seems like something that should definitely be fixed to me.

That being said, I've just noticed another issue with that code too, even prior to the fix - the `size` parameter is completely unused. At a glance, it seems like we should really be using `snprintf` and using the `size` parameter, otherwise there's a risk of buffer overflows.

Thank you for bringing more eyes to this!
